### ISSUE TITLE
anaconda 源的配置是否需要临时加些内容？

### ISSUE THREAD

**Issue by specter119** [sjtug/sjtug.github.io#12]
https://github.com/sjtug/mirror-requests/issues/56 所描情况，现在会很容易出现。`conda` 默认版本已经到了 4.7.10 了，而且主环境的默认自动升级(安装低版本也会默认更新到 4.7.10)。

没有测试官方源是否也存在这个问题，但使用第三方源为了避免这个问题，需要进行如下操作:

- 在 <https://repo.continuum.io/miniconda/> 找到 4.6.16 版本的重新安装，Linux/macOS 可以直接用 `-bfp` + 路径覆盖安装。
- 在 `~/.condarc` 中写上 `auto_update_conda: false`

不知道现在是不是 `.conda` 文件没有同步过来，但就前一段测试来说，官方源也有这个问题。可以等这个问题消失后去掉这个配置，否则现在没法使用。

**Comment by skyzh** [comment]
感谢！我稍后会加到镜像的帮助里面。

**Comment by skyzh** [comment]
https://github.com/sjtug/portal/commit/157cfba8e0924bf0fb88c8261899584c30ae5ade CDN 需要一段时间更新。过几个小时应该就能看到了。

**Comment by specter119** [comment]
首先，是我自己的完整配置。
for linux/mac:
```yaml
channel_alias: https://anaconda.mirrors.sjtug.sjtu.edu.cn/cloud
custom_multichannels:
  sjtu:
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/main
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/r
  tuna:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
channels:
  # - sjtu
  # - tuna
  - defaults
  - conda-forge
  # - pytorch
  # - atztogo
  - viscid-hub
pinned_packages:
  - conda-forge::blas[build=mkl]
  - conda-forge::libblas[build=*mkl]
  - conda-forge::scikit-learn
  - conda-forge::ipympl
  - conda-forge::widgetsnbextension
  - conda-forge::pandas-profiling
  - tensorflow[build=mkl_*,version>=2.0.0]
  - pytorch[build=cpu_*]
  - viscid-hub::vtk
  - viscid-hub::mayavi
  - prompt_toolkit[version<3]
envs_dirs:
  - ~/.conda/envs
pkgs_dirs:
  - ~/.conda/pkgs
```
for win:
```yaml
auto_activate_base: false
channel_alias: https://anaconda.mirrors.sjtug.sjtu.edu.cn/cloud
custom_multichannels:
  sjtu:
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/main
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/r
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/msys2
  tuna:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
channels:
  # - sjtu
  # - tuna
  - defaults
  - conda-forge
  # - pytorch
  # - atztogo
  - viscid-hub
pinned_packages:
  - conda-forge::blas[build=mkl]
  - conda-forge::libblas[build=*mkl]
  - conda-forge::scikit-learn
  - conda-forge::ipympl
  - conda-forge::widgetsnbextension
  - conda-forge::pandas-profiling
  - tensorflow[build=mkl_*,version>=2.0.0]
  - pytorch[build=cpu_*]
  - viscid-hub::vtk
  - viscid-hub::mayavi
  - prompt_toolkit[version<3]
envs_dirs:
  - ~\.conda\envs
pkgs_dirs:
  - ~\.conda\pkgs
  - ~\AppData\Local\Programs\Miniconda\pkgs
```
`channel_alias`  是直接把所有第三方的源链到sjtug上。好处是，第三方源显示的名字就是原来的名字，也不用写很长的url，或者写很多自定义源组。坏处是这么写只能用sjtug里有的第三方源，导致对sjtug依赖更大。不过，注释掉就能回到官方的第三方源，也不是很麻烦。
`custom_multichannels` 定义了 sjtug 和 tuna 源组，win和另外两个平台略有不同。在 `channels` 里写到 `defaults` 之前，就可以既用上 sjtug 源，又不被缺 .conda 的 bug 困扰。
> 因为我提及的几个版本的 conda 里有一个宝藏 bug，好像是会利用官方的 .conda 去解析依赖，然后下载的时候，不管 channels 里有没有被注释，都按先后顺序下载。在 sjtug 恢复正常之前，也请大家务必不要去 conda 报这个 bug，挺好的。

剩下的就是固定版本以及目录的一些设置了，按需求看看就好。
